Import Library

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

Load Datasets

In [2]:
iris = load_iris()
x = iris.data
y = iris.target

print(x.shape)
print(y.shape)
x2 = x[:4]
print(x2)


(150, 4)
(150,)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


Splite Data into Train and Test

In [3]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42, stratify=y)
print("Training Samples:",x_train.shape[0])
print("Testing Samples:",y_train.shape[0])

Training Samples: 105
Testing Samples: 105


Create and Train KNN

In [1]:
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(x_train,y_train)

NameError: name 'KNeighborsClassifier' is not defined

Make Predictions

In [6]:
y_pred = knn.predict(x_test)

print("Predicted ",y_pred)
print("Actual Leb",y_test)

Predicted  [2 1 2 1 2 2 1 1 0 2 0 0 2 2 0 2 1 0 0 0 1 0 1 2 2 1 1 1 1 0 2 2 1 0 2 0 0
 0 0 1 1 0 1 2 1]
Actual Leb [2 1 2 1 2 2 1 1 0 2 0 0 2 2 0 2 1 0 0 0 1 0 1 2 2 1 1 1 1 0 2 2 1 0 2 0 0
 0 0 1 1 0 2 2 1]


Evalution the Model

In [7]:
accuracy = accuracy_score(y_test,y_pred)
print("The accuracy is - ",accuracy )

The accuracy is -  0.9777777777777777


In [8]:
from sklearn.metrics import confusion_matrix,classification_report

cm = confusion_matrix(y_test,y_pred)
print(cm)
cr = classification_report(y_test,y_pred)
print(cr)

[[15  0  0]
 [ 0 15  0]
 [ 0  1 14]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.94      1.00      0.97        15
           2       1.00      0.93      0.97        15

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

